### ISSUE TITLE
History Screen

### ISSUE THREAD

**Issue by IlyaBaudin** [glenchiu1214/nov#1]
No API method for this screen

**Comment by glenchiu1214** [comment]
u mean on pdf  m page 13 (my livestock farming - History page)?

**Comment by glenchiu1214** [comment]
/api/user/report-breeding/{idBreeding}
/api/user/order-breeding/{idBreeding}

**Comment by IlyaBaudin** [comment]
Yes about 13th page in PDF

I implemented this two method in our application. BUT i don't see here a PDFs, no links, no create data, no titles. Only answers with products, and products. See examples. You told that PDFs send server. Can you web guy implement it?  Now this methods not usable.

1.
Request:
[Debug] - Method : http://api.novactiv.dev.ylly.fr/api/user/report-breeding/2.json
Response:
Same as a second.

2.
Request:
[Debug] - Method : http://api.novactiv.dev.ylly.fr/api/user/order-breeding/2.json
Response:
[Debug] - data : [
  {
    "id" : 3,
    "breeding" : {
      "address" : "test1",
      "city" : "test",
      "zip_code" : "59000",
      "id" : 2,
      "lastname" : "test1",
      "firstname" : "test1",
      "phone" : "0999999999",
      "email" : "test1@novactiv.fr",
      "id_herd" : 332,
      "name" : "test1 EDIT"
    },
    "order_product" : [
      {
        "quantity" : 1,
        "id" : 4,
        "price" : 47.68,
        "packaging" : {
          "id" : 6,
          "purchasing_price" : 32,
          "recommended_retail_price" : 47.68,
          "name" : "NOVACTIV SPRAY 10kg",
          "under_packaging" : [

          ]
        }
      },
      {
        "quantity" : 3,
        "id" : 5,
        "price" : 99.98,
        "packaging" : {
          "id" : 7,
          "purchasing_price" : 67.09999999999999,
          "recommended_retail_price" : 99.98,
          "name" : "NOVACTIV SPRAY 22kg",
          "under_packaging" : [

          ]
        }
      },
      {
        "quantity" : 4,
        "id" : 6,
        "price" : 259.26,
        "packaging" : {
          "id" : 8,
          "purchasing_price" : 174,
          "recommended_retail_price" : 259.26,
          "name" : "NOVACTIV SPRAY 60kg",
          "under_packaging" : [

          ]
        }
      }
    ]
  },
  {
    "id" : 2,
    "breeding" : {
      "address" : "test1",
      "city" : "test",
      "zip_code" : "59000",
      "id" : 2,
      "lastname" : "test1",
      "firstname" : "test1",
      "phone" : "0999999999",
      "email" : "test1@novactiv.fr",
      "id_herd" : 332,
      "name" : "test1 EDIT"
    },
    "order_product" : [
      {
        "quantity" : 12,
        "id" : 2,
        "price" : 99.98,
        "packaging" : {
          "id" : 7,
          "purchasing_price" : 67.09999999999999,
          "recommended_retail_price" : 99.98,
          "name" : "NOVACTIV SPRAY 22kg",
          "under_packaging" : [

          ]
        }
      },
      {
        "quantity" : 1,
        "id" : 3,
        "price" : 403.64,
        "packaging" : {
          "id" : 28,
          "purchasing_price" : 270.9,
          "recommended_retail_price" : 403.64,
          "name" : "NOVACTIV XCELL MIX 22kg + 23kg",
          "under_packaging" : [
            {
              "id" : 5,
              "purchasing_price" : 113.78,
              "recommended_retail_price" : 169.52,
              "name" : "NOVACTIV XCELL MIX 22kg"
            },
            {
              "id" : 6,
              "purchasing_price" : 157.12,
              "recommended_retail_price" : 234.12,
              "name" : "NOVACTIV XCELL MIX 23kg"
            }
          ]
        }
      }
    ]
  }
]

**Comment by glenchiu1214** [comment]
web guy  said he didn’t have time to do it. Si that’s normal it doesn’t send pdf’s infos

Web guy will fix it soon

**Comment by IlyaBaudin** [comment]
okay. waiting :)

**Comment by IlyaBaudin** [comment]
web guy fixed that or not?

**Comment by glenchiu1214** [comment]
Not yet. He's working on it.

**Comment by IlyaBaudin** [comment]
see methods.
load and show pdfs ready
