### ISSUE TITLE
Report screen & Product description screen

### ISSUE THREAD

**Issue by IlyaBaudin** [glenchiu1214/nov#2]
No API method which send us product info, product PDFs, report text and other.

**Comment by glenchiu1214** [comment]
-Product will no longer have pdf linked to, only title, description, image
-Api for product is /api/products

**Comment by IlyaBaudin** [comment]
24th pdf page in Corrections
center image with product specification server doesn't send it

37th pdf page in Corrections
we set:
productLogo
productTitle
which data we need to set in textblock under product title
server doesn't send product description image

**Comment by IlyaBaudin** [comment]
![1](https://cloud.githubusercontent.com/assets/1227522/19647441/bbfee2f2-9a06-11e6-97dc-f353a2fe7d1e.png)

images fixed.

**Comment by IlyaBaudin** [comment]
which field contain this text in red border on screen?

**Comment by glenchiu1214** [comment]
It is a field that we added yesterday the field is called "special_description" if it is empty, it is not displayed in the API
