### ISSUE TITLE
My clinic screen

### ISSUE THREAD

**Issue by IlyaBaudin** [glenchiu1214/nov#3]
No API method which send us info about client (№ SAP, Nom de la clinque and others)
![simulator-screen-shot-14- -2016- -13 54 23](https://cloud.githubusercontent.com/assets/1227522/19385213/14b79aae-9216-11e6-9db0-17f2ac40989a.png)

**Comment by IlyaBaudin** [comment]
which API method contain this data?
this GET /api/user/all-info.json?

**Comment by glenchiu1214** [comment]
Is the problem remains now you've access to all-info ?

**Comment by IlyaBaudin** [comment]
No telephone number... all other data is OK

**Comment by glenchiu1214** [comment]
Perhaps, it's because you tried to see with an account on which we didn't add a telephone number.

we add all the clinic accounts a telephone number, so tell me if the problem still remains

**Comment by IlyaBaudin** [comment]
![2016-10-25 11 30 05](https://cloud.githubusercontent.com/assets/1227522/19678435/6c73a34e-9aa6-11e6-8672-2ab3d3f0012d.png)

i don't see a phone number in response.

**Comment by IlyaBaudin** [comment]
it's for api@novactiv.fr user
for maxime@ylly.fr all right.
