### ISSUE TITLE
Add/Edit breeding screen

### ISSUE THREAD

**Issue by IlyaBaudin** [glenchiu1214/nov#4]
Edit screen

![simulator-screen-shot-14- -2016- -13 57 58](https://cloud.githubusercontent.com/assets/1227522/19385305/7e5c0a6c-9216-11e6-8d38-c3d1c188a7b4.png)

1. Server doesn't send idHerd data
API response:
{
    "address" : "Ny 14th avenue",
    "city" : "test",
    "zip_code" : "59000",
    "id" : 14,
    "lastname" : "test surnom",
    "firstname" : "test nom",
    "phone" : "0999999999",
    "email" : "myelevage@gmail.com",
    "name" : "My elevage"
  }

2. I made a PUT request.
But I am not sure that it's working correctly. When I send a PUT request server find a breeding record by idHerd value. But it will be better if server user BreedingID for that.

**Comment by glenchiu1214** [comment]
we added this morning :)

**Comment by IlyaBaudin** [comment]
Yes. Great.
