### ISSUE TITLE
POST /api/create/report

### ISSUE THREAD

**Issue by IlyaBaudin** [glenchiu1214/nov#5]
Not always but sometimes server send a 500 error code.

For this postString all right (code 200)
"reportbreeding[breeding]=2&reportbreeding[answers][0]=47&reportbreeding[answers][1]=49&reportbreeding[answers][2]=53&reportbreeding[answers][3]=56&reportbreeding[answers][4]=59&reportbreeding[answers][5]=61&reportbreeding[answers][6]=63&reportbreeding[answers][7]=65&reportbreeding[answers][8]=76&reportbreeding[answers][9]=78&reportbreeding[answers][10]=80&reportbreeding[answers][11]=83&reportbreeding[answers][12]=85&reportbreeding[answers][13]=66&reportbreeding[answers][14]=69&reportbreeding[answers][15]=71&reportbreeding[answers][16]=73&reportbreeding[answers][17]=75&reportbreeding[products][0]=2&reportbreeding[products][1]=7&reportbreeding[products][2]=5"

But I am not sure if we send this postString (look we have got two products with id=2) server send 500 error. Products in POST parameters can be repeated or not?
"reportbreeding[breeding]=2&reportbreeding[answers][0]=47&reportbreeding[answers][1]=49&reportbreeding[answers][2]=53&reportbreeding[answers][3]=56&reportbreeding[answers][4]=59&reportbreeding[answers][5]=61&reportbreeding[answers][6]=63&reportbreeding[answers][7]=65&reportbreeding[answers][8]=76&reportbreeding[answers][9]=78&reportbreeding[answers][10]=80&reportbreeding[answers][11]=83&reportbreeding[answers][12]=85&reportbreeding[answers][13]=66&reportbreeding[answers][14]=69&reportbreeding[answers][15]=71&reportbreeding[answers][16]=73&reportbreeding[answers][17]=75&reportbreeding[products][0]=2&reportbreeding[products][1]=7&reportbreeding[products][2]=5&reportbreeding[products][3]=2"

**Comment by glenchiu1214** [comment]
it's may be because you put twice the same product sometimes ? either way we are working on it

**Comment by IlyaBaudin** [comment]
do you check it?
we need to send sometimes same products because different answers can contain same products.

**Comment by IlyaBaudin** [comment]
for example
we can select for 
question with ID 24 -> answer with ID 58
question with ID 27 -> answer with ID 64

all other answers is not important
for this situation we have got two answers with one product (id=6)
and if we send it in this API method we need send it twice?? or only one time?

"blabla...&reportbreeding[products][2]=6&reportbreeding[products][3]=6.."
or we must send duplicated products only one time?
"blabla...&reportbreeding[products][2]=6..."

**Comment by glenchiu1214** [comment]
The products added because of answers are special.
It replace the products originally added  from the risks.

Each questions has to be answered before the change of products. 
At the end, the server has to check every answers and decide each risk is the most present. With that, it will determine which products  have to be displayed. I tried to explain it visually.

![image](https://cloud.githubusercontent.com/assets/22402488/19663522/f56c460e-9a44-11e6-8a57-233c708d1bee.png)

Tell me if it's not clear.

**Comment by IlyaBaudin** [comment]
we need to send to server changed(final) products???

now i send products from answers
and how i can understand we need to set all answers, then analyse risks, change products if it's needed and then this changed products send to server, yes?
