### ISSUE TITLE
Signin screen

### ISSUE THREAD

**Issue by IlyaBaudin** [glenchiu1214/nov#6]
![simulator-screen-shot-14- -2016- -14 13 47](https://cloud.githubusercontent.com/assets/1227522/19385730/e4614ffa-9218-11e6-86a6-ec65bd98a3e1.png)

1. which API request we need to use when user tap on forgot button?
2. user filled email and password - how we can check that this user exist in our system?
3. about authorisation procedure can you write step by step how it's work for random user? now we use user data for api@novactiv.fr
so how i can understand

- user filled email & password
- then we get user salt from server
- then encode password with salt
- then send requests with header which we made

but when i try to send POST /api/user/salt.json without wsse header i see 403 response code.

4. how should work "remember me" button?
if user set "remember me" he can logout only with disconnect button
if user not set "remember me" when we must logout user? when he close application? or when app became inactive and go to foreground?

**Comment by glenchiu1214** [comment]
1. /api/user/reset-password & /api/user/reset-password-change

3. You got it right, but you have to call /api/user/salt.json with api WSSE first, then when you got the salt you only use user WSSE

**Comment by IlyaBaudin** [comment]
1. we need to create a special controller for password change???
2. i try to use /api/user/salt with APIWSSE but server send me a 204 error code (No content)

**Comment by glenchiu1214** [comment]
1. we need to create a special controller for password change??? —> 
there’s no password change. But the password has to be hide (now it’s visible, I can read password). Please transform you text field in a password input

2.i try to use /api/user/salt with APIWSSE but server send me a 204 error code (No content) —> Have you still a problem with that ?

**Comment by glenchiu1214** [comment]
It's a changing in 2 steps "WEB". firstly,  you need to do the WES /api/user/reset-password.{_format} (see the example below)
![image](https://cloud.githubusercontent.com/assets/22402488/19677626/d8d0ead2-9aa2-11e6-99d5-bda63b0def1d.png)

then, you use the answer from WES and use it in the second WES /api/user/reset-password-change.{_format}
![image](https://cloud.githubusercontent.com/assets/22402488/19677631/e402ae90-9aa2-11e6-9560-83293208f190.png)

With the password visible (you see the letters) and twice to verify they are identical

**Comment by IlyaBaudin** [comment]
methods salt, and change password working now
it's not working for api@novactiv.fr and doc user but for maxime@ylly.fr it's working good

questions about SaveMe checkbox
how it must work???
if we set it app save current user
if we don't set it when app must logout? when user app became foreground or when app terminated?

**Comment by glenchiu1214** [comment]
Only way for the user to logout is to press on the logout button, which will be somewhere in the app.

If save me was checked at login and user logout, when come back on the app it should see his email and password filled already

**Comment by glenchiu1214** [comment]
Normally you should use the account "api@novactiv.fr" to the request of then salt must be used as a clinical account "maxime@ylly.fr". The account api should not normally have information related to this account. That is why there is no phone number

**Comment by IlyaBaudin** [comment]
Good. Thank you.
