### ISSUE TITLE
Corrections issue

### ISSUE THREAD

**Issue by IlyaBaudin** [glenchiu1214/nov#7]
All pages from Corrections PDF
6th page - number of diagnostic. server doesn't send this data in app.
now we have got a new diagnostic and if the last diagnostic didn't finished we continue it

14th page - please check it again. i tested it on my real iPad. values saved successfully 

15th page - this formula is correct??? i fixed it as in PDF. but i am not sure that logic of this formula is correct

17th page - so we need to change default value for margin rate on 33%???

19th page - which api method contain data about my clinic?

21th page - please check it again. i tested it yesterday - all working without any problems.

25th page - i don't understand it. they want that when we want to create new breeding we set the last field №ID indentifiant cheptel from any data from server???

29th page - please change images on server side... now images has a low resolution and looks bad

32th page - no image for product description

**Comment by glenchiu1214** [comment]
All pages from Corrections PDF

6th page - number of diagnostic. server doesn't send this data in app.
now we have got a new diagnostic and if the last diagnostic didn't finished we continue it  
—> Web guy put the id. So you’ll have the info*

14th page - please check it again. i tested it on my real iPad. values saved successfully 
—>I tried again and have no problem today. Just forget this slide, I'll put it after "correction done"

15th page - this formula is correct??? i fixed it as in PDF. but i am not sure that logic of this formula is correct
 —> This is another way to find the same result.  In this one, please put the margin rate in %. taux de marge% (margin rate%) = (prix d’achat {initial price}/ prix de vente conseillé{retail price})x100 /// Prix de vente conseillé{retail price} = prix d’achat{initial price} + taux de marge% (margin rate%)

17th page - so we need to change default value for margin rate on 33%???
—> yes, it’ll be easier for the vets

19th page - which api method contain data about my clinic?
—> /api/user/all-info

21th page - please check it again. i tested it yesterday - all working without any problems.
—> Same as the  one on page 14th. 

25th page - i don't understand it. they want that when we want to create new breeding we set the last field №ID indentifiant cheptel from any data from server??? 
—> we want the breedings informations to be attached to 1 and only clinic. In the BO, we’ll see for each vet, the different breedings and on the app, each vet will only see his breedings.

29th page - please change images on server side... now images has a low resolution and looks bad 
—>I changed the pictures

32th page - no image for product description 
—> I don’t understand. It's a text, not an image.

**Comment by IlyaBaudin** [comment]
All pages in new PDF corrections
7th page 
which method send us this data? 
![7](https://cloud.githubusercontent.com/assets/1227522/19591102/f7dd1e0a-977d-11e6-82bf-363b2956c236.png)

11th page
i suggest you and your client add a small animation here. when we open existing diagnostic show animation when it loads and after that hide it. something like this. it's only template, when i implement it in our project it will be more  beatifull
![11](https://cloud.githubusercontent.com/assets/1227522/19591221/84d05430-977e-11e6-8804-4adeb3e9da4d.png)

15th page
i implement formula which was in corrections presentation
you can check it

19th page
mmm... now we init this block using api method get/user/all-info
 "id": 11,
  "username": "doc@novactiv.fr",
  "email": "doc@novactiv.fr",
  "enabled": true,
  "last_login": "2016-10-20T16:44:16+0200",
  "firstname": "doc",
  "lastname": "doc",
  "address": "74 rue des arts",
  "zip_code": 59000,
  "city": "Lille",
  "clinique_info": {
    "id": 1,
    "code_sap": 224,
    "clinique_name": "TEST"
  },
i am not undestand what's wrong. it they want to set in this all fields all info about clinic not user we need to add some fields in clinique_info block

now i init this block using this code
numberSap.text = "\(ServerManager.sharedManager.userInformation.clinic!.codeSnap!)"
clinicName.text = ServerManager.sharedManager.userInformation.clinic?.cliniqName!
clinicAddress.text = ServerManager.sharedManager.userInformation.address!
zipCode.text = "\(ServerManager.sharedManager.userInformation.zipCode!)"
city.text = ServerManager.sharedManager.userInformation.city!
telephoneNumber.text = "No info"
email.text = ServerManager.sharedManager.userInformation.email!

and there is no telephone number.

25th page
check this slide
![25](https://cloud.githubusercontent.com/assets/1227522/19591362/51fa53e8-977f-11e6-81ce-351b6a5c79e5.png)


26th page
now we use last field which user filled as a idHerd(vet id?)
and clinicID we use userInformation.userID
not understand this issue

38th page
check this slide
![38](https://cloud.githubusercontent.com/assets/1227522/19591464/e6940440-977f-11e6-8fc5-c1a0ade80ebb.png)


and please check Signup issue. 
post /salt send me a 204 error
now we can login as a api@novactiv.fr
we need to change it for all users

thank you very much

**Comment by glenchiu1214** [comment]
7th page 
=> Web guy attributes an id, so you can find the data.

11th page
=> because the loading takes some time ? Is it needed ?

15th page
=> I will. thanks

19th page
=> Telephone number added

=> It's a bit complicated. In fact, vet are clinics. It's countryside clinics and one vet will enter the infos but all the vets of the clinic will use the same account. So, in clinic informations page, it will be : 

Code sap (in clinic info)
Clinic name (in clinic info)
Address (in profile info)
zip_code(in profile info)
City(in profile info)
Phone number (in profile info)

25th page
=> it's an image. It's in the BO. I'll see with Max if everything's ok  for you to see. I don"t know when you noticed this problem (I put the images in the BO on Friday afternoon). Please check again on your side, I'll check too on mine.

26th page
=> breedings are linked to clinics/vet. In "Créer un nouvel élevage"(create a new breeding), you have the breeding informations, not the vet one. Is it clear ? If not, tell me please.
